# Generated by Django 4.1.5 on 2023-04-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=25)),
                ('Email', models.CharField(max_length=50)),
                ('Message', models.TextField()),
            ],
        ),
    ]
