# Generated by Django 4.1.5 on 2023-04-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='spic',
            field=models.ImageField(null=True, upload_to='static/slider/'),
        ),
    ]
