# Generated by Django 4.1.5 on 2023-04-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_slider_spic'),
    ]

    operations = [
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vhead', models.CharField(max_length=100)),
                ('vdes', models.CharField(max_length=300)),
                ('vlink', models.CharField(max_length=500)),
                ('vpic', models.ImageField(default='', upload_to='static/videos/')),
            ],
        ),
    ]
