# Generated by Django 4.1.5 on 2023-04-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='bnews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bhead', models.CharField(max_length=300)),
                ('bdate', models.DateField()),
                ('bdes', models.TextField()),
                ('bpic', models.ImageField(default='', upload_to='static/bnews/')),
            ],
        ),
    ]
